"""Step 3 of Nina's voice: turns the WAVs recorded by synth.ps1 into a child's voice.

Each recording is sped up by FACTOR. Unlike the browser's pitch setting, which only raises the note of
the voice, speeding the audio up also raises its timbre (the formants) - and that is what tells a
child's voice from a grown-up speaking high. The clips are then trimmed, levelled and saved as MP3 in
public/voice/, and src/kids/voiceClips.js lists which lines have a recording.

Needs: pip install numpy lameenc
"""
import json
import sys
import wave
from pathlib import Path

import lameenc
import numpy as np

# 1.4 takes the voice to about 280 Hz, a young child's pitch (grown-up women speak around 200 Hz).
FACTOR = float(sys.argv[1]) if len(sys.argv) > 1 else 1.4
HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
WAV_DIR = HERE / 'build' / 'wav'
OUT_DIR = ROOT / 'public' / 'voice'
CLIPS_JS = ROOT / 'src' / 'kids' / 'voiceClips.js'


def lowpass(signal, cutoff_hz, rate, taps=129):
    """Windowed-sinc low-pass, so squeezing the audio in time doesn't fold high frequencies back down."""
    fc = cutoff_hz / rate
    n = np.arange(taps) - (taps - 1) / 2
    kernel = np.sinc(2 * fc * n) * np.blackman(taps)
    kernel /= kernel.sum()
    return np.convolve(signal, kernel, mode='same')


def childify(samples, rate):
    x = samples - samples.mean()
    x = lowpass(x, 0.92 * (rate / 2) / FACTOR, rate)
    positions = np.arange(0, len(x) - 1, FACTOR)
    y = np.interp(positions, np.arange(len(x)), x)
    # Trim the silence the speech engine leaves around each line, keeping a short breath.
    loud = np.flatnonzero(np.abs(y) > 0.02 * np.abs(y).max())
    if loud.size:
        margin = int(0.04 * rate)
        y = y[max(0, loud[0] - margin): loud[-1] + margin]
    y = y / (np.abs(y).max() or 1) * 0.89  # about -1 dB peak, every line equally loud
    fade = min(len(y) // 4, int(0.01 * rate))
    if fade:
        ramp = np.linspace(0, 1, fade)
        y[:fade] *= ramp
        y[-fade:] *= ramp[::-1]
    return y


def to_mp3(samples, rate):
    encoder = lameenc.Encoder()
    encoder.set_bit_rate(48)
    encoder.set_in_sample_rate(rate)
    encoder.set_channels(1)
    encoder.set_quality(2)
    pcm = (np.clip(samples, -1, 1) * 32767).astype('<i2').tobytes()
    return encoder.encode(pcm) + encoder.flush()


def main():
    lines = json.loads((HERE / 'build' / 'lines.json').read_text(encoding='utf-8'))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_DIR.glob('*.mp3'):
        old.unlink()
    ids = []
    total = 0
    for line in lines:
        path = WAV_DIR / f"{line['id']}.wav"
        with wave.open(str(path), 'rb') as wav:
            rate = wav.getframerate()
            raw = wav.readframes(wav.getnframes())
        samples = np.frombuffer(raw, dtype='<i2').astype(np.float64) / 32768
        mp3 = to_mp3(childify(samples, rate), rate)
        (OUT_DIR / f"{line['id']}.mp3").write_bytes(mp3)
        ids.append(line['id'])
        total += len(mp3)
    listed = ',\n'.join(f"  '{i}'" for i in sorted(ids))
    CLIPS_JS.write_text(
        '// Generated by scripts/nina-voice (childify.py): the lines Nina has a recording for, in public/voice/.\n'
        f'export const VOICE_CLIPS = new Set([\n{listed},\n]);\n',
        encoding='utf-8',
    )
    print(f'{len(ids)} falas em {OUT_DIR} ({total / 1024:.0f} KB), fator {FACTOR}')


if __name__ == '__main__':
    main()
